### ISSUE TITLE
Cannot install daemonupgradecontroller via readme

### ISSUE THREAD

**Issue by ahrechanychenko** [Mirantis/k8s-daemonupgradecontroller#7]
I'm try to install ds controller via manual
https://github.com/Mirantis/k8s-daemonupgradecontroller/blob/master/README.md

vagrant@node1:~/k8s-daemonsetupgradecontroller$ make build
go get github.com/Masterminds/glide
package github.com/Masterminds/glide: cannot download, $GOPATH not set. For more details see: go help gopath
Makefile:91: recipe for target 'vendor' failed
make: *** [vendor] Error 1

So please update readme and provide full info for installing

**Comment by ahrechanychenko** [comment]
I know that I need to do next steps:
sudo apt-get install mercurial make goland
mkdir -p golang/src/github.com/Mirantis
cd golang/src/github.com/Mirantis/
git clone https://github.com/Mirantis/k8s-daemonupgradecontroller
export GOPATH=~/golang
mkdir $GOPATH/bin
export PATH=$PATH:$GOPATH/bin

but I think that need to describe some info about that necessary to setup goland and export GOPATH

**Comment by levor23** [comment]
also next issues 

vagrant@node1:~/golang/src/github.com/Mirantis/k8s-daemonupgradecontroller$ make build
mkdir -p _output
go get github.com/Masterminds/glide
glide install --strip-vendor
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching github.com/go-openapi/jsonpointer.
[INFO]	--> Fetching github.com/dgrijalva/jwt-go.
[INFO]	--> Fetching github.com/go-openapi/jsonreference.
[INFO]	--> Fetching bitbucket.org/ww/goautoneg.
[INFO]	--> Fetching cloud.google.com/go.
[INFO]	--> Fetching github.com/Azure/go-ansiterm.
[INFO]	--> Fetching github.com/beorn7/perks.
[INFO]	--> Fetching github.com/blang/semver.
[INFO]	--> Fetching github.com/coreos/go-oidc.
[INFO]	--> Fetching github.com/coreos/pkg.
[INFO]	--> Fetching github.com/davecgh/go-spew.
[INFO]	--> Fetching github.com/docker/go-units.
[INFO]	--> Fetching github.com/docker/distribution.
[INFO]	--> Fetching github.com/docker/docker.
[INFO]	--> Fetching github.com/docker/engine-api.
[INFO]	--> Fetching github.com/docker/go-connections.
[INFO]	--> Fetching github.com/emicklei/go-restful.
[INFO]	--> Fetching github.com/docker/spdystream.
[INFO]	--> Fetching github.com/exponent-io/jsonpath.
[INFO]	--> Fetching github.com/ghodss/yaml.
[WARN]	Unable to checkout bitbucket.org/ww/goautoneg
[ERROR]	Update failed for bitbucket.org/ww/goautoneg: hg is not installed
[INFO]	--> Fetching github.com/go-openapi/spec.
[INFO]	--> Fetching github.com/go-openapi/swag.
[INFO]	--> Fetching github.com/gogo/protobuf.
[INFO]	--> Fetching github.com/golang/glog.
[INFO]	--> Fetching github.com/golang/groupcache.
[INFO]	--> Fetching github.com/golang/protobuf.
[INFO]	--> Fetching github.com/google/gofuzz.
[INFO]	--> Fetching github.com/howeyc/gopass.
[INFO]	--> Fetching github.com/imdario/mergo.
[INFO]	--> Fetching github.com/jonboulle/clockwork.
[INFO]	--> Fetching github.com/juju/ratelimit.
[INFO]	--> Fetching github.com/mailru/easyjson.
[INFO]	--> Fetching github.com/matttproud/golang_protobuf_extensions.
[INFO]	--> Fetching github.com/mitchellh/go-wordwrap.
[INFO]	--> Fetching github.com/onsi/ginkgo.
[INFO]	--> Fetching github.com/onsi/gomega.
[INFO]	--> Fetching github.com/pborman/uuid.
[INFO]	--> Fetching github.com/prometheus/client_golang.
[INFO]	--> Fetching github.com/prometheus/client_model.
[INFO]	--> Fetching github.com/prometheus/common.
[INFO]	--> Fetching github.com/prometheus/procfs.
[INFO]	--> Fetching github.com/PuerkitoBio/purell.
[INFO]	--> Fetching github.com/PuerkitoBio/urlesc.
[INFO]	--> Fetching github.com/Sirupsen/logrus.
[INFO]	--> Fetching github.com/spf13/pflag.
[INFO]	--> Fetching github.com/ugorji/go.
[INFO]	--> Fetching golang.org/x/crypto.
[INFO]	--> Fetching golang.org/x/net.
[INFO]	--> Fetching golang.org/x/oauth2.
[INFO]	--> Fetching golang.org/x/sys.
[INFO]	--> Fetching golang.org/x/text.
[INFO]	--> Fetching google.golang.org/appengine.
[INFO]	--> Fetching gopkg.in/inf.v0.
[INFO]	--> Fetching gopkg.in/yaml.v2.
[INFO]	--> Fetching k8s.io/kubernetes.
[ERROR]	Failed to install: hg is not installed
Makefile:91: recipe for target 'vendor' failed
make: *** [vendor] Error 1

**Comment by ahrechanychenko** [comment]
vagrant@node1:~/golang/src/github.com/Mirantis/k8s-daemonupgradecontroller$ make docker
make: *** No rule to make target 'docker'.  Stop
